Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 103, in on_ready
    await send_greeting(bot)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 138, in on_message
    await send_greeting(bot, channel)
  File "./bot.py", line 108, in send_greeting
    if channel.name in bot.g.no_greeting:
  File "/home/pi/gamePicker/properties.py", line 6, in getter
    return self[key]
KeyError: 'no_greeting'
ready
saved
saved
saved
saved
saved
saved
saved
saved
saved
saved
saved
saved
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "poob" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "how" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "you" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "aaaaaaaaaaaaaaaaaaaaaaaaaaaa" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "aaaaaaaaaaa" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "bo.op" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "poob" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "woof" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "foof" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "foof" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "hello" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "hi" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "allow" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "hi" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "hi" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "go" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "bot" is not found
ready
